/**
 * 支持的语言列表
 */
const LANGUAGES = [
    { "name": "English", "value": "en" },
    { "name": "简体中文", "value": "zh-cn" },
    { "name": "繁體中文", "value": "zh-tw" },
    { "name": "Afrikaans", "value": "af" },
    { "name": "shqiptar", "value": "sq" },
    { "name": "አማርኛ", "value": "am" },
    { "name": "عربى", "value": "ar" },
    { "name": "հայերեն", "value": "hy" },
    { "name": "Azərbaycan", "value": "az" },
    { "name": "Euskal", "value": "eu" },
    { "name": "беларускі", "value": "be" },
    { "name": "বাঙালি", "value": "bn" },
    { "name": "Bosanski", "value": "bs" },
    { "name": "български", "value": "bg" },
    { "name": "Català", "value": "ca" },
    { "name": "Cebuano", "value": "ceb" },
    { "name": "Chichewa", "value": "ny" },
    { "name": "Corsu", "value": "co" },
    { "name": "Hrvatski", "value": "hr" },
    { "name": "čeština", "value": "cs" },
    { "name": "dansk", "value": "da" },
    { "name": "Nederlands", "value": "nl" },
    { "name": "Esperanto", "value": "eo" },
    { "name": "Eesti keel", "value": "et" },
    { "name": "Filipino", "value": "tl" },
    { "name": "Suomalainen", "value": "fi" },
    { "name": "français", "value": "fr" },
    { "name": "Frysk", "value": "fy" },
    { "name": "Galego", "value": "gl" },
    { "name": "ქართული", "value": "ka" },
    { "name": "Deutsche", "value": "de" },
    { "name": "Ελληνικά", "value": "el" },
    { "name": "ગુજરાતી", "value": "gu" },
    { "name": "Kreyòl Ayisyen", "value": "ht" },
    { "name": "Hausa", "value": "ha" },
    { "name": "ʻŌlelo Hawaiʻi", "value": "haw" },
    { "name": "עִברִית", "value": "iw" },
    { "name": "हिंदी", "value": "hi" },
    { "name": "Hmoob", "value": "hmn" },
    { "name": "Magyar", "value": "hu" },
    { "name": "Íslensku", "value": "is" },
    { "name": "Igbo", "value": "ig" },
    { "name": "bahasa Indonesia", "value": "id" },
    { "name": "Gaeilge", "value": "ga" },
    { "name": "italiano", "value": "it" },
    { "name": "日本語", "value": "ja" },
    { "name": "Wong Jawa", "value": "jw" },
    { "name": "ಕನ್ನಡ", "value": "kn" },
    { "name": "Қазақша", "value": "kk" },
    { "name": "ភាសាខ្មែរ", "value": "km" },
    { "name": "한국어", "value": "ko" },
    { "name": "Kurdî (Kurmancî)", "value": "ku" },
    { "name": "Кыргызча", "value": "ky" },
    { "name": "ລາວ", "value": "lo" },
    { "name": "Latine", "value": "la" },
    { "name": "Latviešu", "value": "lv" },
    { "name": "Lietuviškai", "value": "lt" },
    { "name": "lëtzebuergesch", "value": "lb" },
    { "name": "Македонски", "value": "mk" },
    { "name": "Malagasy", "value": "mg" },
    { "name": "Melayu", "value": "ms" },
    { "name": "മലയാളം", "value": "ml" },
    { "name": "Malti", "value": "mt" },
    { "name": "Maori", "value": "mi" },
    { "name": "मराठी", "value": "mr" },
    { "name": "Монгол хэл", "value": "mn" },
    { "name": "မြန်မာ (ဗမာ)", "value": "my" },
    { "name": "नेपाली", "value": "ne" },
    { "name": "norsk", "value": "no" },
    { "name": "پښتو", "value": "ps" },
    { "name": "فارسی", "value": "fa" },
    { "name": "Polskie", "value": "pl" },
    { "name": "Português", "value": "pt" },
    { "name": "Punjabi", "value": "ma" },
    { "name": "Română", "value": "ro" },
    { "name": "русский", "value": "ru" },
    { "name": "Samoa", "value": "sm" },
    { "name": "Gàidhlig na h-Alba", "value": "gd" },
    { "name": "Српски", "value": "sr" },
    { "name": "Sesotho", "value": "st" },
    { "name": "Shona", "value": "sn" },
    { "name": "سنڌي", "value": "sd" },
    { "name": "සිංහල", "value": "si" },
    { "name": "slovenský", "value": "sk" },
    { "name": "Slovenščina", "value": "sl" },
    { "name": "Somali", "value": "so" },
    { "name": "Español", "value": "es" },
    { "name": "Sunda", "value": "su" },
    { "name": "Kiswahili", "value": "sw" },
    { "name": "svenska", "value": "sv" },
    { "name": "Тоҷикӣ", "value": "tg" },
    { "name": "தமிழ்", "value": "ta" },
    { "name": "తెలుగు", "value": "te" },
    { "name": "ไทย", "value": "th" },
    { "name": "Türk", "value": "tr" },
    { "name": "Українська", "value": "uk" },
    { "name": "اردو", "value": "ur" },
    { "name": "O'zbek", "value": "uz" },
    { "name": "Tiếng Việt", "value": "vi" },
    { "name": "Cymraeg", "value": "cy" },
    { "name": "isiXhosa", "value": "xh" },
    { "name": "ייִדיש", "value": "yi" },
    { "name": "Yorùbá", "value": "yo" },
    { "name": "Zulu", "value": "zu" }
]
